name: Deploy docs

on: workflow_dispatch

jobs:
  deploy_docs:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "build-storybook-docs"

  update_chromatic_permalink_in_readme:
    name: "Update chromatic permalink in README.md"
    runs-on: ubuntu-latest
    needs: deploy_docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Exposes metadata as environment variable
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Update chromatic permalink
        uses: varunsridharan/action-dynamic-readme@main
        with:
          commit_message: "docs: update chromatic permalink in README.md"
          committer_name: "v.voloshin"
          committer_email: "viktor_the_great@mail.ru"
          global_template_repository: "${{ github.repository_owner }}/${{ github.repository_name }}"
          files: |
            .github/readme-templates/README.md=README.md
        env:
          CHROMATIC_PERMALINK: "https://${{ env.SHORT_SHA }}--${{ vars.CHROMATIC_PROJECT_ID }}.chromatic.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write