name: Deploy docs
on:
  push:
    tags:
      - 'v*.*.*'
env:
  USER_NAME: ${{ vars.USER_NAME || 'github-actions[bot]' }}
  USER_EMAIL: ${{ vars.USER_EMAIL || 'github-actions[bot]@users.noreply.github.com' }}
  STORYBOOK_SIDEBAR_VISIBILITY: ${{ vars.STORYBOOK_SIDEBAR_VISIBILITY || 'visible' }}
  STORYBOOK_TOOLBAR_VISIBILITY: ${{ vars.STORYBOOK_TOOLBAR_VISIBILITY || 'visible' }}
  DEPLOY_BRANCH: ${{ vars.DEPLOY_BRANCH || 'gh-pages' }}
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  queue: max

jobs:
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      deployment: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm' # Adjust caching strategy and configuration if using other package managers
      - name: Deploy docs
        run: .bin/deploy-docs.sh
